# Generated by Django 5.1.15 on 2026-04-14 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('check_in_date', models.DateField(help_text='Expected check-in date')),
                ('check_out_date', models.DateField(help_text='Expected check-out date')),
                ('num_guests', models.IntegerField(default=1, help_text='Number of guests')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('source', models.CharField(choices=[('direct', 'Direct / Walk-in'), ('phone', 'Phone'), ('website', 'Website'), ('booking_com', 'Booking.com'), ('agoda', 'Agoda'), ('traveloka', 'Traveloka'), ('tiket_com', 'Tiket.com'), ('expedia', 'Expedia'), ('airbnb', 'Airbnb'), ('other', 'Other OTA')], default='direct', help_text='How this booking was made', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='Guest special requests')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('actual_check_in', models.DateTimeField(blank=True, help_text='Actual check-in timestamp', null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, help_text='Actual check-out timestamp', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(help_text='The guest making the reservation', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('rate', models.DecimalField(decimal_places=0, help_text='Nightly rate for this room in this reservation (IDR)', max_digits=12)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rooms', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Reservation Room',
                'verbose_name_plural': 'Reservation Rooms',
                'unique_together': {('reservation', 'room')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(help_text='Rooms assigned to this reservation', related_name='reservations', through='reservations.ReservationRoom', to='rooms.room'),
        ),
    ]
