# Generated by Django 5.1.15 on 2026-04-14 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Auto-generated invoice number (e.g., INV/2026/04/0001)', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('reservation', models.OneToOneField(help_text='The reservation this folio belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('charge_type', models.CharField(choices=[('room', 'Room Charge'), ('fnb', 'Food & Beverage'), ('minibar', 'Minibar'), ('laundry', 'Laundry'), ('spa', 'Spa'), ('transport', 'Transport'), ('telephone', 'Telephone'), ('other', 'Other')], default='room', max_length=20)),
                ('description', models.CharField(help_text='Description of the charge (e.g., "Room 101 — Night 1")', max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Charge amount in IDR', max_digits=12)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity (e.g., number of nights)')),
                ('is_taxable', models.BooleanField(default=True, help_text='Whether PB1 tax applies to this charge')),
                ('folio', models.ForeignKey(help_text='Which folio this charge belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.folio')),
                ('posted_by', models.ForeignKey(blank=True, help_text='Staff member who posted this charge', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folio Charge',
                'verbose_name_plural': 'Folio Charges',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Payment amount in IDR', max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('qris', 'QRIS'), ('ota_collect', 'OTA Collected'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Transaction reference (card last 4, transfer ref, etc.)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('folio', models.ForeignKey(help_text='Which folio this payment applies to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.folio')),
                ('received_by', models.ForeignKey(blank=True, help_text='Staff member who received this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=0, help_text='Total taxable amount', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate applied (e.g., 10.00)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=0, help_text='Calculated tax amount', max_digits=12)),
                ('service_charge_amount', models.DecimalField(decimal_places=0, default=0, help_text='Service charge amount', max_digits=12)),
                ('period_month', models.IntegerField(help_text='Tax period month (1-12)')),
                ('period_year', models.IntegerField(help_text='Tax period year')),
                ('folio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_record', to='billing.folio')),
            ],
            options={
                'verbose_name': 'Tax Record',
                'verbose_name_plural': 'Tax Records',
                'ordering': ['-period_year', '-period_month'],
            },
        ),
    ]
