# Generated by Django 5.1.15 on 2026-04-14 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('full_name', models.CharField(help_text='Full name as on ID', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(help_text='Phone number', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_type', models.CharField(choices=[('ktp', 'KTP (Indonesian ID)'), ('passport', 'Passport'), ('sim', 'SIM (Driving License)'), ('other', 'Other')], default='ktp', help_text='Type of identification document', max_length=20)),
                ('id_number', models.CharField(help_text='KTP number, passport number, etc.', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Indonesia', help_text='Country of origin (for APOA reporting)', max_length=100)),
                ('nationality', models.CharField(default='Indonesian', help_text='Nationality (for immigration compliance)', max_length=100)),
                ('is_vip', models.BooleanField(default=False, help_text='VIP guest flag')),
                ('notes', models.TextField(blank=True, help_text='Special requests, preferences, dietary needs, etc.')),
                ('total_stays', models.IntegerField(default=0, help_text='Number of times this guest has stayed')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['full_name'],
            },
        ),
    ]
