# Generated by Django 5.1.15 on 2026-04-14 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('name', models.CharField(help_text='Supplier company name', max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('name', models.CharField(help_text='Item name', max_length=200)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit code', max_length=50, unique=True)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('ltr', 'Liters'), ('box', 'Boxes'), ('pack', 'Packs'), ('btl', 'Bottles'), ('roll', 'Rolls'), ('set', 'Sets')], default='pcs', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, help_text='Cost per unit in IDR', max_digits=12)),
                ('current_stock', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('min_stock_level', models.IntegerField(default=10, help_text='Minimum stock level (triggers alert below this)')),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase (In)'), ('usage', 'Usage (Out)'), ('adjustment', 'Adjustment'), ('waste', 'Waste/Spoilage'), ('return', 'Return to Supplier')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity moved')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, help_text='Cost per unit at time of transaction', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Reference (e.g., PO number, room number, POS order)', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
