# Generated by Django 5.1.15 on 2026-04-14 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('task_type', models.CharField(choices=[('checkout_clean', 'Check-out Cleaning'), ('stayover_clean', 'Stayover Cleaning'), ('deep_clean', 'Deep Cleaning'), ('maintenance', 'Maintenance'), ('inspection', 'Inspection')], default='checkout_clean', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('inspected', 'Inspected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Task notes or issues found')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='Room to be cleaned/maintained', on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Housekeeping Task',
                'verbose_name_plural': 'Housekeeping Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
