# Generated by Django 5.1.15 on 2026-04-14 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('name', models.CharField(help_text='e.g., Deluxe, Suite, Villa', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this room type')),
                ('base_rate', models.DecimalField(decimal_places=0, help_text='Base nightly rate in IDR (e.g., 1500000)', max_digits=12)),
                ('max_occupancy', models.IntegerField(default=2, help_text='Maximum number of guests')),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities (e.g., AC, WiFi, TV, Minibar, Pool Access)')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['base_rate'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('room_number', models.CharField(help_text='Room number (e.g., 101, 201A)', max_length=10, unique=True)),
                ('floor', models.IntegerField(default=1, help_text='Floor number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('dirty', 'Dirty'), ('maintenance', 'Maintenance'), ('out_of_order', 'Out of Order')], default='available', help_text='Current room status', max_length=20)),
                ('rate_override', models.DecimalField(blank=True, decimal_places=0, help_text='Override nightly rate (leave blank to use room type base rate)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this room')),
                ('room_type', models.ForeignKey(help_text='Which type of room this is', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['floor', 'room_number'],
            },
        ),
    ]
