# Generated by Django 5.1.15 on 2026-04-14 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('inventory', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, help_text='Price in IDR', max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pos.menucategory')),
                ('inventory_item', models.ForeignKey(blank=True, help_text='Linked inventory item for auto stock deduction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('payment_type', models.CharField(choices=[('room_charge', 'Charge to Room'), ('cash', 'Cash'), ('card', 'Card'), ('qris', 'QRIS')], default='room_charge', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folio', models.ForeignKey(blank=True, help_text='Folio to charge (auto-linked from room)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='billing.folio')),
                ('room', models.ForeignKey(blank=True, help_text='Room to charge (if room_charge payment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='rooms.room')),
            ],
            options={
                'verbose_name': 'POS Order',
                'verbose_name_plural': 'POS Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp. Null means active.', null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, help_text='Price at time of order (in case menu price changes)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Special instructions')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posorder')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
